services:
    server:
        container_name: adda-server
        image: dipan2003/adda:latest
        ports:
            - "8008:8008"
            - "42000-42100:42000-42100/udp" # ⭐ Mediasoup RTC ports
            - "42000-42100:42000-42100/tcp" # ⭐ Mediasoup RTC ports
        env_file:
            - .env
        restart: always
